export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";

export const SEARCH_LIST_REQUEST = "SEARCH_LIST_REQUEST";
export const SEARCH_LIST_SUCCESS = "SEARCH_LIST_SUCCESS";
export const SEARCH_LIST_FAIL = "SEARCH_LIST_FAIL";

export const SEARCH_SUGGESTION_REQUEST = "SEARCH_SUGGESTION_REQUEST";
export const SEARCH_SUGGESTION_SUCCESS = "SEARCH_SUGGESTION_SUCCESS";
export const SEARCH_SUGGESTION_FAIL = "SEARCH_SUGGESTION_FAIL";
