export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
export const PRODUCT_LIST_BY_CATEGORY_REQUEST =
  "PRODUCT_LIST_BY_CATEGORY_REQUEST";
export const PRODUCT_LIST_BY_CATEGORY_SUCCESS =
  "PRODUCT_LIST_BY_CATEGORY_SUCCESS";
export const PRODUCT_LIST_BY_CATEGORY_FAIL = "PRODUCT_LIST_BY_CATEGORY_FAIL";

export const PRODUCT_DETAIL_BY_PATH_REQUEST = "PRODUCT_DETAIL_BY_PATH_REQUEST";
export const PRODUCT_DETAIL_BY_PATH_SUCCESS = "PRODUCT_DETAIL_BY_PATH_SUCCESS";
export const PRODUCT_DETAIL_BY_PATH_FAIL = "PRODUCT_DETAIL_BY_PATH_FAIL";
