export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
export const PRODUCT_LIST_BY_CATEGORY_SUCCESS =
  "PRODUCT_LIST_BY_CATEGORY_SUCCESS";
export const PRODUCT_LIST_BY_CATEGORY_FAIL = "PRODUCT_LIST_BY_CATEGORY_FAIL";
